### ISSUE TITLE
Error at start about modular_single

### ISSUE THREAD

**Issue by H4Mm3r** [mickelus/tetra#147]
## Bug Report

**Observed Behaviour**
Error at start

Crash log: 
[18:47:51] [Server thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe tetra:earthpiercer
com.google.gson.JsonSyntaxException: Unknown item 'tetra:modular_single'
        at net.minecraft.item.crafting.ShapedRecipe.lambda$deserializeItem$0(ShapedRecipe.java:264) ~[?:?] {re:classloading}
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212] {}
        at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:263) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:283) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1432) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:436) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:351) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

**Minimal setup needed to reproduce**
- Forge version: 
- Tetra version: tetra-1.14.4-1.26.0.jar

**Comment by mickelus** [comment]
Sorry, I've messed up and didn't test with the default config values. If you want to play before I'm able to provide a patch you can update `config/tetra.toml`, replace the line that says `single_headed = false` with `single_headed = true`.

**Comment by H4Mm3r** [comment]
Is that file automatically generated ? I don't find it

**Comment by H4Mm3r** [comment]
Seems working. I'll keep an eye on your update. Thanks.

**Comment by mickelus** [comment]
Changed this to default to true for 1.14.

**Comment by H4Mm3r** [comment]
Thanks !
