### ISSUE TITLE
1.15.2-[DEDICATED SERVER crash due to a missing item from tetra bugging out refined storage]

### ISSUE THREAD

**Issue by SDUBZ** [mickelus/tetra#160]
## Bug Report
crash due to a missing item from tetra bugging out refined storage
**Observed Behaviour**
crashes during loading due to a item you removed bugs out refined storage

crash report:
https://github.com/raoulvdberge/refinedstorage/files/4581189/crash-2020-04-30_16.48.04-client.txt

**Expected Behaviour**
to load like normal

**Minimal setup needed to reproduce**
well you cant since its a modpack and a server world
- Forge version: 1.15.2
- Tetra version:  tetra-1.15.2-2.5.0
- Tetra configuration: 
[tetra.txt](https://github.com/mickelus/tetra/files/4586171/tetra.txt)

- Other mods:
[mods.txt](https://github.com/mickelus/tetra/files/4586177/mods.txt)

**Steps to reproduce**
not quite sure how you can

all other relavite information can be found here : https://github.com/raoulvdberge/refinedstorage/issues/2509

**Comment by mickelus** [comment]
I'm unable to reproduce this with just tetra and refined storage. The error in the log you've provided is related to neither tetra or refined storage.

What does "due to a item you removed" mean?

**Comment by SDUBZ** [comment]
a item from tetra it seems the refined storage dev noticed it in the debug i sent them

**Comment by SDUBZ** [comment]
this the thing that gets spammed when the world is loading ``` at se.mickelus.tetra.items.modular.ItemModular.getMaxDamage(ItemModular.java:99) ~[?:1.15.2-2.5.0]
	at net.minecraft.item.ItemStack.func_77958_k(ItemStack.java:248) ~[?:?]
	at se.mickelus.tetra.items.modular.ItemModular.setDamage(ItemModular.java:408) ~[?:1.15.2-2.5.0]
	at net.minecraft.item.ItemStack.func_196085_b(ItemStack.java:244) ~[?:?]
	at net.minecraft.item.ItemStack.func_77982_d(ItemStack.java:489) ~[?:?]
	at se.mickelus.tetra.NBTHelper.getTag(NBTHelper.java:18) ~[?:1.15.2-2.5.0]
	at se.mickelus.tetra.items.modular.ItemModular.getAllModules(ItemModular.java:130) ~[?:1.15.2-2.5.0]
	at se.mickelus.tetra.items.modular.ItemModular.getMaxDamage(ItemModular.java:99) ~[?:1.15.2-2.5.0]
	at net.minecraft.item.ItemStack.func_77958_k(ItemStack.java:248) ~[?:?]
	at se.mickelus.tetra.items.modular.ItemModular.setDamage(ItemModular.java:408) ~[?:1.15.2-2.5.0]
	at net.minecraft.item.ItemStack.func_196085_b(ItemStack.java:244) ~[?:?]
	at net.minecraft.item.ItemStack.func_77982_d(ItemStack.java:489) ~[?:?]
	at se.mickelus.tetra.NBTHelper.getTag(NBTHelper.java:18) ~[?:1.15.2-2.5.0] ```

**Comment by SDUBZ** [comment]
new logs:
[debug.log](https://github.com/mickelus/tetra/files/4603286/debug.log)
[latest.log](https://github.com/mickelus/tetra/files/4603287/latest.log)

**Comment by SDUBZ** [comment]
@mickelus hope the new logs help you debug what is happening

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/mickelus/tetra/files/4608236/latest.log)
This is even happening on a new fresh world

**Comment by SlimJefe** [comment]
Also having crash on dedicated sever. Removing Tetra fixes it for me. Crash Log: https://pastebin.com/50VP4J8e

**Comment by mickelus** [comment]
Still unable to reproduce this, feel free to reopen if you're able to describe how to reproduce this.
