### ISSUE TITLE
Datapack load failed

### ISSUE THREAD

**Issue by Cheaterpaul** [mickelus/tetra#219]
## Bug Report

**Observed Behaviour**
Datapack load failed

Crash log: [debug_2.log](https://github.com/mickelus/tetra/files/5426510/debug_2.log) line 9701

**Expected Behaviour**
load the datapack without error

**Minimal setup needed to reproduce**

- Forge version:1.14.4-28.2.23
- Tetra version: 1.14.4-1.27.0
- Tetra configuration: ?
- Other mods: modpack https://www.curseforge.com/minecraft/modpacks/web-of-time

**Steps to reproduce**
start up the game and load world

**Comment by Cheaterpaul** [comment]
^^the error occures even without vampirism

**Comment by mickelus** [comment]
If there's an error in your datapack then you'll have to fix that, I can't do that for you.

**Comment by Cheaterpaul** [comment]
this is not an error in my datapack.

you are loading values from datapacks which crashes, resulting in all not laoded datapack are ignored

**Comment by Cheaterpaul** [comment]
see here 
`Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[server-1.14.4-extra-stable.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.14.4-extra-stable.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.14.4-extra-stable.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[server-1.14.4-extra-stable.jar:?]
	at se.mickelus.tetra.data.DataStore.lambda$parseData$2(DataStore.java:121) ~[?:1.14.4-1.27.0]`

**Comment by mickelus** [comment]
I've seen the error, there's an array in a place that should contain an object, which is very much an error in your (or another) datapack. The datapack parser can't magically understand what you want to do, you need to provide data in the expected format.
