### ISSUE TITLE
Beta 3.5.1 - Fatal ticking on player, server kicks.

### ISSUE THREAD

**Issue by Deightine** [mickelus/tetra#298]
## Bug Report

**Observed Behaviour**
After the recent .1 fix, the server will load, but it won't accept my character in particular. I haven't had a chance to test with other players, but reading the log suggests its something Tetra-made in my inventory causing it to break when it tries to load me up. But that is a wild guess--you'll know your class paths better than I.

**Crash log:** 

`[04Jan2021 10:36:03.338] [Server thread/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent net/minecraft/client/gui/AbstractGui for class se/mickelus/mgui/gui/GuiElement in classloader cpw.mods.modlauncher.TransformingClassLoader@7e4579c7 on thread Thread[Server thread,5,SERVER]
--
[04Jan2021 10:36:03.338] [Server thread/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: net.minecraft.client.gui.AbstractGui
at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~odlauncher-8.0.6.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-3.0.5-service.jar:3.0.5+64+master.ec454d4]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.6.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-3.0.5-service.jar:3.0.5+64+master.ec454d4]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.6.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at se.mickelus.tetra.items.modular.ModularItem.func_77663_a(ModularItem.java:467) ~[tetra:3.5.1]
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:431) ~[?:?]
at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:238) ~[?:?]
at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:487) ~[?:?]
at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Suppressed: java.lang.ClassNotFoundException
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.6.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-3.0.5-service.jar:3.0.5+64+master.ec454d4]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.6.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-3.0.5-service.jar:?]
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-3.0.5-service.jar:3.0.5+64+master.ec454d4]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.6.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.6.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at se.mickelus.tetra.items.modular.ModularItem.func_77663_a(ModularItem.java:467) ~[tetra:3.5.1]
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:431) ~[?:?]
at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:238) ~[?:?]
at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:487) ~[?:?]
at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[04Jan2021 10:36:03.360] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID *Redacted*
[04Jan2021 10:36:03.361] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /*Redacted*:50491
net.minecraft.crash.ReportedException: Ticking player`

**Expected Behaviour**
Login, followed by play.

**Minimal setup needed to reproduce**

- Forge version: 35.1.2
- Tetra version: 3.5.1
- Tetra configuration: No custom config.
- Other mods:

**Steps to reproduce**
I have a -lot- of tetra tools. The rarest of the lot is a Trident with a load of spell enchantments on it, but I have a tool for each purpose. Pickaxe, an adze, a long shovel, long blade, crossbow, and trident. Not using the belt, at the moment though. Just tools. 

**Troubleshooting...**
To verify it was an on-item-load issue, I removed my player file from the server and loaded in fresh. It loaded without a fatal tick. So either this update isn't able to take as an upgrade (which will need a release note), or something isn't parsing right as it loads, due to changes in those items. But that's all on the other side of the curtain from me.

**Comment by Deightine** [comment]
And... somehow I missed that there was a crash report for this up already. Two in fact. Feel free to merge or close it. But I'll leave it for now so you have the info, as one of the others was pretty sparse.

**Comment by Rainemakerx** [comment]
I can further verify that this kick/fatal tick is happening as soon as any tetra modular tool is picked up.

**Comment by mickelus** [comment]
Should be fixed for real in 3.5.2!
