### ISSUE TITLE
Unexpected Crash caused by terrain generation within tetra

### ISSUE THREAD

**Issue by Razzamatter** [mickelus/tetra#316]
## Bug Report

**Observed Behaviour**
I was traveling towards the coordinates shown below in the pasted whole crash report when the game froze up and crashed. I'm not very knowledgeable on reading crash reports so I don't know the details of it but it seemed as though the game was trying to generate something in the terrain in a certain chunk where an issue was caused by the tetra mod. I don't know if the tetra mod tried to generate terrain or if terrain generation somehow conflicted with it. the attached crash report should also list all mods that are being used with it. 

It's worth noting the issue was 'fixed' by removing the tetra mod. I am convinced that the tetra mod is the cause of this issue, or it was caused by a conflict with another mod. I do not have enough information to figure out which.
Crash log: 
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/15/21 3:25 AM
Description: Feature placement

java.lang.ClassCastException: net.minecraft.world.gen.WorldGenRegion cannot be cast to net.minecraft.world.World
	at melonslise.subwild.common.block.SpeleothemBlock.func_196271_a(SpeleothemBlock.java:100) ~[?:1.1.1] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:655) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.gen.feature.template.Template.lambda$func_222857_a$4(Template.java:358) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template$$Lambda$10260/1303875281.consume(Unknown Source) ~[?:?] {}
	at net.minecraft.util.math.shapes.VoxelShapePart.func_211541_a(SourceFile:313) ~[?:?] {re:classloading}
	at net.minecraft.util.math.shapes.VoxelShapePart.func_211540_a(SourceFile:282) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.func_222857_a(Template.java:348) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:312) ~[?:?] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generateFeature(FeatureEntry.java:208) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.lambda$generateChildren$3(FeatureEntry.java:245) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry$$Lambda$10371/1124937331.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at se.mickelus.tetra.generation.FeatureEntry.generateChildren(FeatureEntry.java:224) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generateFeature(FeatureEntry.java:215) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generateFeatureRoot(FeatureEntry.java:178) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generate(FeatureEntry.java:146) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.func_241855_a(FeatureEntry.java:49) ~[?:3.5.3] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.environs.json:MixinBiome,pl:mixin:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2299/1807835051.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$9003/76134602.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$9000/952637516.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$8945/1019202899.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at melonslise.subwild.common.block.SpeleothemBlock.func_196271_a(SpeleothemBlock.java:100) ~[?:1.1.1] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:655) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.gen.feature.template.Template.lambda$func_222857_a$4(Template.java:358) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template$$Lambda$10260/1303875281.consume(Unknown Source) ~[?:?] {}
	at net.minecraft.util.math.shapes.VoxelShapePart.func_211541_a(SourceFile:313) ~[?:?] {re:classloading}
	at net.minecraft.util.math.shapes.VoxelShapePart.func_211540_a(SourceFile:282) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.func_222857_a(Template.java:348) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:312) ~[?:?] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generateFeature(FeatureEntry.java:208) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.lambda$generateChildren$3(FeatureEntry.java:245) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry$$Lambda$10371/1124937331.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at se.mickelus.tetra.generation.FeatureEntry.generateChildren(FeatureEntry.java:224) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generateFeature(FeatureEntry.java:215) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generateFeatureRoot(FeatureEntry.java:178) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.generate(FeatureEntry.java:146) ~[?:3.5.3] {re:classloading}
	at se.mickelus.tetra.generation.FeatureEntry.func_241855_a(FeatureEntry.java:49) ~[?:3.5.3] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
-- Feature --
Details:
	Id: tetra:feature
	Config: net.minecraft.world.gen.feature.NoFeatureConfig@34bfcf06
	Description: se.mickelus.tetra.generation.FeatureEntry@72f112d1
Stacktrace:
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.environs.json:MixinBiome,pl:mixin:A}

-- Generation --
Details:
	CenterX: -37
	CenterZ: 54
	Seed: -832139288452130047
	Biome: net.minecraft.world.biome.Biome@38905461
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2299/1807835051.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}

-- Chunk to be generated --
Details:
	Location: -37,54
	Position hash: 236223201243
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@37fa6837
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$9003/76134602.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$9000/952637516.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$8945/1019202899.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Chiliblue'/110, l='ServerLevel[Modded Exploration]', x=-509.67, y=69.00, z=658.17]]
	Chunk stats: ServerChunkCache: 4139
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,64,-2), Chunk: (at 0,4,14 in -8,-1; contains blocks -128,0,-16 to -113,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 765494 game time, 967255 day time
	Level name: Modded Exploration
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 108893 (now: false), thunder time: 168159 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$8707/752365837.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 643413152 bytes (613 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.4_HD_U_G6_pre11.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.10.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.10
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.10-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		tetra-1.16.4-3.5.3.jar                            |Tetra                         |tetra                         |3.5.3               |DONE      |NOSIGNATURE
		TreeChop-1.16.4-0.11.3.jar                        |treechop                      |treechop                      |0.11.3              |DONE      |NOSIGNATURE
		repurposed_structures-1.16.4-2.3.3.jar            |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.3        |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		easierenchanting-1.4.0.jar                        |Easier Enchanting             |easierenchanting              |1.4.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.4-3.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		BetterCaves-1.16.3-1.0.6.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.3-1.0.6        |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.0.0_Forge_1.16.4.jar            |Xaero's Minimap               |xaerominimap                  |21.0.0              |DONE      |NOSIGNATURE
		leap-1.16.4-1.0.1.jar                             |Leap                          |leap                          |1.0.1               |DONE      |NOSIGNATURE
		gravestone-1.16.4-1.0.8.jar                       |Gravestone Mod                |gravestone                    |1.16.4-1.0.8        |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		polymorph-forge-1.16.4-0.22.jar                   |Polymorph                     |polymorph                     |1.16.4-0.22         |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		jumbofurnace-1.16.4-2.2.0.1.jar                   |Jumbo Furnace                 |jumbofurnace                  |1.16.4-2.2.0.1      |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		outvoted-1.16.4-1.0.3.jar                         |Outvoted                      |outvoted                      |1.0.3               |DONE      |NOSIGNATURE
		ItemPhysic_v1.4.14_mc1.16.4.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |NOSIGNATURE
		The_Undergarden-1.16.4-0.4.3.jar                  |The Undergarden               |undergarden                   |0.4.3               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.10-universal.jar                |Forge                         |forge                         |35.1.10             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		inventoryhotswap-1.16-1.2.jar                     |Inventory Hotswap             |inventoryhotswap              |1.0                 |DONE      |NOSIGNATURE
		supplementaries-0.9.19.jar                        |Supplementaries               |supplementaries               |0.9.19              |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.3-1.1.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1.1        |DONE      |NOSIGNATURE
		SubWild-1.16.4-1.1.1.jar                          |Subterranean Wilderness       |subwild                       |1.1.1               |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.3.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.3      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
	Crash Report UUID: ce09ed6f-5124-49cf-9cef-69b2fd27e2b0
	Player Count: 1 / 8; [ServerPlayerEntity['Chiliblue'/110, l='ServerLevel[Modded Exploration]', x=-509.67, y=69.00, z=658.17]]
	Data Packs: vanilla, mod:tetra, mod:treechop, mod:repurposed_structures, mod:creativecore, mod:easierenchanting, mod:jei, mod:abnormals_core, mod:buzzier_bees, mod:upgrade_aquatic, mod:savageandravage, mod:bettercaves (incompatible), mod:xaerominimap, mod:leap (incompatible), mod:gravestone, mod:mgui (incompatible), mod:polymorph, mod:citadel (incompatible), mod:endergetic, mod:outvoted, mod:itemphysic, mod:undergarden, mod:forge, mod:inventoryhotswap, mod:supplementaries, mod:bettermineshafts (incompatible), mod:subwild, mod:geckolib3 (incompatible), mod:dsurround (incompatible), mod:jumbofurnace (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.4_HD_U_G6_pre11
	OptiFine Build: 20210110-173522
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.79
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
**Expected Behaviour**
chunks to load in normally 

**Minimal setup needed to reproduce**

- Forge version: 35.1.10
- Tetra version: tetra-1.16.4-3.5.3
- Tetra configuration: default
- Other mods:

**Steps to reproduce**
going to the coordinates provided in the crash report on the provided seed with the tetra mod installed and possibly other provided mods as well

**Comment by mickelus** [comment]
Looks like the crash is occuring in subterranean wilderness, this seem to be a duplicate of https://github.com/Melonslise/Subterranean-Wilderness/issues/14.

**Comment by mickelus** [comment]
Closing this as there's nothing I can do to fix it on my side.
