### ISSUE TITLE
tetra-1.16.5-3.8.0.jar not correctly detecting curio dependency with curios-forge-1.16.5-4.0.5.1-api.jar

### ISSUE THREAD

**Issue by BuruzuTheBlue** [mickelus/tetra#398]
No full report. 
Tetra displays in the minecraft gui that it only works with curio 4 or higher, but is not working with any curio version for 1.16.5.

**Comment by ItsGarek** [comment]
`---- Minecraft Crash Report ----
// My bad.

Time: 4/24/21, 2:12 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:95) [mohist.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:92) [mohist.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:89) [mohist.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:89) ~[forge:?] {re:classloading}
-- MOD tetra --
Details:
	Mod File: tetra-1.16.5-3.8.0.jar
	Failure message: Mod tetra only supports curios 4 or above
		Currently, curios is 1.16.5-4.0.5.1
	Mod Version: 3.8.0
	Mod Issue URL: https://github.com/mickelus/tetra/issues/new
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:89) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:87) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:95) [mohist.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:92) [mohist.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:89) [mohist.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-1028-gcp
	Java Version: 11.0.10, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 6921853184 bytes (6601 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 2
	JVM Flags: 8 total; -XX:+UseG1GC -Xmx7G -Xms7G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/mohist.jar object_holder_definalize PLUGINSERVICE 
		/mohist.jar runtime_enum_extender PLUGINSERVICE 
		/mohist.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/mohist.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/mohist.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.13
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.11.0
	Mod List: 
		forge-1.16.5-36.1.13-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |NONE      |NOSIGNATURE
		forge-1.16.5-36.1.13-universal.jar                |Forge                         |forge                         |36.1.13             |NONE      |NOSIGNATURE
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs
`

**Comment by ocram9** [comment]
This is because of a forge update, specfically this merge: https://github.com/MinecraftForge/MinecraftForge/pull/7710

Downgrading to forge 31.1.9 is a temporary fix.

**Comment by KatoNamus** [comment]
Came to report this, busy downgrading forge. I case it helps, I have submitted details and logs to Forge support at [https://forums.minecraftforge.net/topic/100076-possible-bug-report-forge-1165-36110-optional-dependency-mod-versions/](url)

**Comment by mickelus** [comment]
Fixed in 3.9.0
