### ISSUE TITLE
Crash when trying to open a chest

### ISSUE THREAD

**Issue by m-vlad** [mickelus/tetra#438]
## Bug Report

**Observed Behaviour**
I found this derelict structure underground, it's half sliced by the worldgen. Trying to right click with the hammer on the lock crashes the game. This is the second chest I found, but the first one that crashed the game. Filling up the space around as if the wall and floor are still there does nothing.
![image](https://user-images.githubusercontent.com/22298459/120246659-c86e6f00-c268-11eb-8326-7e05f7b98045.png)

Crash log:
```
java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=flipped, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:cave_air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at se.mickelus.tetra.blocks.forged.container.ForgedContainerTile.getUpdatedBlockState(ForgedContainerTile.java:141) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.forged.container.ForgedContainerTile.updateBlockState(ForgedContainerTile.java:137) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.forged.container.ForgedContainerTile.breakLock(ForgedContainerTile.java:197) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.forged.container.ForgedContainerBlock.breakLock(ForgedContainerBlock.java:132) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.forged.container.ForgedContainerBlock.lambda$static$0(ForgedContainerBlock.java:63) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.salvage.BlockInteraction.applyOutcome(BlockInteraction.java:109) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.salvage.BlockInteraction.attemptInteraction(BlockInteraction.java:150) ~[tetra:3.11.1] {re:classloading}
	at se.mickelus.tetra.blocks.forged.container.ForgedContainerBlock.func_225533_a_(ForgedContainerBlock.java:156) ~[tetra:3.11.1] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:block.MixinAbstractBlockstate,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:valhelsia_structures.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:288) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1366) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.24.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
```

**Expected Behaviour**
For the locks to break and the game not to crash

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.1.24
- Tetra version: 3.11.1
- Tetra configuration: Default
- Other mods: Since there's a random chance for this to happen, I would have to include the entire mod list (I can do that, but I think this might just be a case of an "if block = air !flipped". Let me know if you need it still.

**Steps to reproduce**
Find dungeon with broken worldgen, try to open it?

**Comment by mickelus** [comment]
The right-half of the chest isn't actually there, which is why it crashes.  I'm guessing you've got quark installed and that's a quark cave you're in?

**Comment by m-vlad** [comment]
In terms of cave generation, yes I have quark and YUNG's collection.

**Comment by belathus** [comment]
Looks like I had a similar crash: https://gist.github.com/belathus/3d65e1f39c09b245987a064390f524a1

**Comment by Shadowex3** [comment]
Had the same exact crash but I think I caused it by using "carry on" to pick up the chest by accident. After setting it back down again it causes the crash.
