### ISSUE TITLE
[Bug] Geodes will not break with Blood Magic installed. [1.18.2]

### ISSUE THREAD

**Issue by VyProductions** [mickelus/tetra#650]
### Observed behaviour

In Tetra 1.18.2-4.9.3 with Blood Magic 1.18.2-3.2.4-39, attempting to break open Tetra geodes fails to produce an item in the player inventory, though it uses durability on a player's T2+ hammer.

@mickelus identified the conflict of Blood Magic through the following error:

```
[05:55:51] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@257a686e, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.storage.loot.LootContext.m_78953_(net.minecraft.world.level.storage.loot.parameters.LootContextParam)" is null
	at wayoftime.bloodmagic.loot.GlobalLootModifier$VoidingModifier.doApply(GlobalLootModifier.java:319) ~[BloodMagic-1.18.2-3.2.4-39.jar%2358!/:1.18.2-3.2.4-39]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1244) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at se.mickelus.tetra.blocks.workbench.action.ConfigActionImpl.perform(ConfigActionImpl.java:86) ~[tetra-1.18.2-4.9.3.jar%23122!/:4.9.3]
	at se.mickelus.tetra.blocks.workbench.WorkbenchTile.lambda$performAction$12(WorkbenchTile.java:226) ~[tetra-1.18.2-4.9.3.jar%23122!/:4.9.3]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at se.mickelus.tetra.blocks.workbench.WorkbenchTile.performAction(WorkbenchTile.java:203) ~[tetra-1.18.2-4.9.3.jar%23122!/:4.9.3]
	at se.mickelus.tetra.blocks.workbench.action.WorkbenchActionPacket.handle(WorkbenchActionPacket.java:50) ~[tetra-1.18.2-4.9.3.jar%23122!/:4.9.3]
	at se.mickelus.mutil.network.PacketHandler.lambda$onMessage$2(PacketHandler.java:75) ~[mutil-1.18.2-4.5.0.jar%23101!/:4.5.0]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at se.mickelus.mutil.network.PacketHandler.onMessage(PacketHandler.java:73) ~[mutil-1.18.2-4.5.0.jar%23101!/:4.5.0]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.1.69-universal.jar%23137!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Expected behaviour

The geode in the workbench should disappear and an item from its loot table should appear in the player's inventory.

### Steps to reproduce

1. Place down a crafting table.
2. Convert it into a Tetra workbench.
3. Place a geode in the workbench and have a T2+ hammer in your inventory.
4. Attempt to "Break open" the geode.

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.69

### Other mods

 AdvancementPlaques-1.18.2-1.4.5.1.jar
ExtendedCrafting-1.18.2-4.1.1.jar
Placebo-1.18.2-6.5.1.jar
comforts-forge-1.18.2-5.0.0.4.jar
mutil-1.18.2-4.5.0.jar
Apotheosis-1.18.2-5.3.6.jar
FarmersDelight-1.18.2-1.1.2.jar
PuzzlesLib-v3.3.5-1.18.2-Forge.jar
cookingforblockheads-forge-1.18.2-12.0.2.jar
polymorph-forge-1.18.2-0.44.jar
BloodMagic-1.18.2-3.2.4-39.jar
FastLeafDecay-28.jar
Runelic-Forge-1.18.2-11.0.1.jar
curios-forge-1.18.2-5.0.7.1.jar
refinedstorage-1.10.3.jar
Bookshelf-Forge-1.18.2-13.2.47.jar
Iceberg-1.18.2-1.0.44.jar
Snad-1.18.2-1.22.04.15a.jar
easy_villagers-1.18.2-1.0.11.jar
selene-1.18.2-1.17.9.jar
Botania-1.18.2-434.jar
InventoryHud_[1.18].forge-3.4.4.jar
StorageDrawers-1.18.2-10.2.1.jar
enderchests-1.18-1.9.6.jar
shetiphiancore-1.18-3.10.10.jar
ChiselsBits-forge-1.18.2-1.2.113-universal.jar
JustEnoughProfessions-1.18.2-1.2.2.jar
TipTheScales-forge-1.18.2-5.0.6.jar
endertanks-1.18-1.11.7.jar
stalwart-dungeons-1.18.2-1.2.2.jar
Clumps-forge-1.18.2-8.0.0+15.jar
JustEnoughResources-1.18.2-0.14.1.171.jar
ToolStats-Forge-1.18.2-9.0.3.jar
ensorcellation-1.18.2-1.6.1.8.jar
structure_gel-1.18.2-2.4.6.jar
Controlling-forge-1.18.2-9.0+21.jar
Mekanism-1.18.2-10.2.5.465.jar
TradingPost-v3.2.0-1.18.2-Forge.jar
gravestone-1.18.2-1.0.1.jar
supplementaries-1.18.2-1.4.8.jar
Croptopia-1.18.2-FORGE-2.0.5.jar
MouseTweaks-forge-mc1.18-2.21.jar
VisualWorkbench-v3.3.0-1.18.2-Forge.jar
ironchest-1.18.2-13.1.9.jar
swingthroughgrass-1.18.2-1.9.0.jar
Cucumber-1.18.2-5.1.2.jar
MysticalAgriculture-1.18.2-5.1.1.jar
advancedperipherals-1.18.2-0.7.16b.jar
ironfurnaces-1.18.2-3.3.1.jar
tetra-1.18.2-4.9.3.jar
Cyclic-1.18.2-1.7.6.jar
NaturesCompass-1.18.2-1.9.7-forge.jar
appleskin-forge-mc1.18-2.4.0.jar
jeed-1.18.2-1.11.jar
theoneprobe-1.18-5.1.0.jar
DarkUtilities-Forge-1.18.2-10.0.5.jar
Neat-1.8-31.jar
balm-3.2.0+0.jar
jei-1.18.2-9.7.1.232.jar
trashslot-forge-1.18.1-11.0.2.jar
EasyMagic-v3.3.0-1.18.2-Forge.jar
NethersDelight-1.18.2-2.2.0.jar
blue_skies-1.18.2-1.3.12.jar
jeiintegration_1.18.2-9.0.0.37.jar
upgradedcore-1.18.2-3.2.0.0-release.jar
EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar
OreExcavation-1.10.162.jar
cc-tweaked-1.18.2-1.100.9.jar
journeymap-1.18.2-5.8.5-forge.jar
upgradednetherite-1.18.2-4.2.0.6-release.jar
EquipmentCompare-1.18.1-1.2.12.jar
Patchouli-1.18.2-71.1.jar
cfm-7.0.0-pre29-1.18.2.jar
modnametooltip-1.18.1-1.18.0.jar
waystones-forge-1.18.2-10.1.0.jar

**Comment by VyProductions** [comment]
For conciseness in the report, I have isolated a specific error.

If needed, here is the entire log file that contained the original error and similar errors.
[2022-08-08-5.log](https://github.com/mickelus/tetra/files/9282254/2022-08-08-5.log)
